### ISSUE TITLE
LD-350 support status?

### ISSUE THREAD

**Issue by ggatward** [knaggsy2000/stormforce#1]
Hi Danny,  Wondering how you are tracking with LD-350 support in SXR ?
I notice an amount of code that references the LD-350, possibly being compatible with the supported EFM100 but I can't get it to fire up. Looks like you are currently expecting an LD-250 to be present.
I do have a 350 here I can connect up and let you play with remotely if it helps at all.  Would love to decommission my last windows server that is only running NexStorm :)

Cheers,
Geoff  VK2XJG

**Comment by knaggsy2000** [comment]
Hi there!  LD-350 is experimental and not even tested as I don't own the actual hardware :(.  Plus, there is only a base-class for the LD-350 in the code, it's not known anywhere else.

EFM-100 is 100% supported, btw.  Has been for quite a while.

However, I believe the LD-350 should still work with the LD-250 base code (I wrote the class based on the API document Boltek provided), but I can't validate that it works.

Try changing line 882 in sxr_server.py from: -

self.ldunit = LD250(self.LD250_PORT, self.LD250_SPEED, self.LD250_BITS, self.LD250_PARITY, self.LD250_STOPBITS, self.LD250_SQUELCH, self.sentenceRX, self.DEBUG_MODE)

to: -

self.ldunit = LD**3**50(self.LD250_PORT, self.LD250_SPEED, self.LD250_BITS, self.LD250_PARITY, self.LD250_STOPBITS, self.LD250_SQUELCH, self.sentenceRX, self.DEBUG_MODE)

Then set the 250 settings in the XML file to point to your 350.  You may find it works fine, or not.

Nice to see that someone is still using SXR ^^.

Danny - 2E0DPK.

**Comment by ggatward** [comment]
Hi Danny,

Thanks for the reply...

I did try simply changing the ldunit string as suggested, but no joy.
After a bit more digging I suspect that the LD350 is NOT a USB Serial
device, given it has a dedicated DLL in windows to control the comms. I can
attach it to my Ubuntu server as a device (/dev/boltek) using udev rules,
but SXR won't have a bar of talking to it, inappropriate ioctl for device
errors, which I believe indicate that the serial methods won't work to the
usb device type :-(

A poke around on Boltek's site I found the Linux SDK, but this looks like
it's only for thier PCI card, and won't compile on my system.

Doesn't look like there's anyone else that has tried to get the LD350
working under Linux, so at the moment I may be stuck with the old Windows
server after all.

Cheers,
Geoff

**Comment by knaggsy2000** [comment]
Sorry for the very late reply, been occupied with other things.

Without myself owning the actual hardware I can't see exactly what's going on and I can't afford the hardware at this time.  Until I do, I won't be able to find out how to get it working.

I'm currently working on new version of StormForce so I'm currently occupied with that - watch this space.

**Comment by vk-hca** [comment]
Sorry this an old thread but as its about ld-350 and they dont get mentioned much I will add to it.
I have had one for years now along with Lightning2000 software. The reason I went for that model was the cat 5 interface and the optional relay outputs only to find later it was of no use on cat 5 without a discontinued GPS module. I am very happy with it in that form but annoyed to be stuck with a USB and worse windows only on a 24/7 device. Had I known this at the time I simply would have ordered the LTS3 GPS timestamp card.
So I have been looking into ways to get the data from it directly over the years, but all solutions are complex.

The LD350 has to be Bolteks biggest balls up! 
It is a great piece of kit and performs excellently, and you have configurable alarm relay outputs available which works well. But your stuck with lame USB, why no serial port, not even a header? They fit it with a functioning cat 5 network interface and no way to use it, with out the gps timestamp card option. Only a limited number of users would be planning a network of receivers with a time stamp, but plenty could use a TCP port. If only they had the foresight to provide the same data as the USB on a TCP port, and serial on the unused GPS header port. Its only firmware problem. An easy upgrade.
  
I have looked closely at hijacking the usb, but its not a passive intervention because you have to send a keep alive once a second.

Its probably easier to replace the FTDI chip with a MCU of some kind and create a fake driver from the SDK  for the USB only WIN client software or drive the FTI chip on a pass through in the MCU. That may not be easy as it sounds with LT2K or any other software that uses raw AtoD data, not the firmware.

So I am wondering if there has been any change on the LT350 side of your project since this was started?

**Comment by siller174** [comment]
Hi @vk-hca @knaggsy2000,
I'm currently working on supporting the LD-350 protocol and was wondering if you'd be interested in taking a look or maybe even trying it out?

Also, if you happen to have an LD-350 device, would you be open to a few questions? I'd really appreciate any help!
